
import java.sql.*; 
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
 import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;
/*
import javax.swing.JFrame;
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import BackEnd.DatabaseConnectionFactory;
import BackEnd.IDatabaseConnection;

 

/**
 *
 * @author mnsso
 */
 
 

public class Statistics extends javax.swing.JFrame {

    /**
     * Creates new form AddNewBook
     */
    public Statistics() {
        initComponents();
//         StudentsBooksPieChart();
//         LendingStatsChart();
//        lendedbook();
//         returnedbook();
//         totalbooks();
//         totalstudents();
           this.setLocationRelativeTo(null);
        setExtendedState(ABORT);
        }
     
       
public static Connection CreateConnection() {
    try {
        IDatabaseConnection connectionStatistics = DatabaseConnectionFactory.getConnection("MYSQL");
        connectionStatistics.connect();
        return connectionStatistics.getConnection();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Connection Error: " + e.getMessage());
        return null;
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        jTable2.setBackground(new java.awt.Color(51, 51, 51));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable4.setBackground(new java.awt.Color(51, 51, 51));
        jTable4.setForeground(new java.awt.Color(255, 255, 255));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jTable3.setBackground(new java.awt.Color(51, 51, 51));
        jTable3.setForeground(new java.awt.Color(255, 255, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(jTable3);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setLocation(new java.awt.Point(700, 550));
        setUndecorated(true);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel1.setAlignmentY(8.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(3, 180));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Lucida Bright", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("© 2025 MNS70 | Github:(MnsDew). All rights reserved. ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/try.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 360, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/bookwhiter.png"))); // NOI18N
        jLabel12.setText("-");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 320, 10));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/bar-chart.png"))); // NOI18N
        jLabel4.setText("l");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 0, 255));
        jButton1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Lent Books Details & Returned Book Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 500, 40));

        jButton3.setBackground(new java.awt.Color(153, 0, 255));
        jButton3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Students Details & Books Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 500, 40));

        jButton4.setBackground(new java.awt.Color(102, 0, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/close .png"))); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 110, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 510, 10));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 0, 204));
        jButton5.setText("Statistics");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 0, 255));
        jButton2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 60, 40));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jButton6.setBackground(new java.awt.Color(153, 0, 255));
        jButton6.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 50, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/forall.jpeg"))); // NOI18N
        jLabel5.setText("0");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -220, 1150, 900));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    
//      public void lendedbook(){
////    String query = "SELECT lend.bookID, student.name, lend.lend_date, lend.due_date FROM lend JOIN student ON lend.studentID = student.studentID WHERE return_status = 'No' ";
//  String query = "SELECT lend.studentID,student.name,lend.bookID,book.BookName,lend.lend_date,lend.due_date from student inner join book inner join lend where book.bookID = lend.bookID and student.studentID = lend.studentID and lend.return_status = 'No' " ;
//    try (
//            Connection conn = CreateConnection();
//            PreparedStatement stmt = conn.prepareStatement(query);
//         ResultSet rs = stmt.executeQuery()) {
// 
//          jTable2.setModel(DbUtils.resultSetToTableModel(rs)); // Set the table model
//        
//          conn.close();
//
//        
//    } catch (SQLException e) {
//        e.printStackTrace();
//     JOptionPane.showMessageDialog(null, "Database Error lending books: " + e.getMessage());
//    }
//      }
//    
//          public void returnedbook(){
////    String query = "SELECT lend.bookID, student.name, lend.lend_date, lend.due_date FROM lend JOIN student ON lend.studentID = student.studentID WHERE return_status = 'No' ";
//  String query = "SELECT lend.studentID,student.name,lend.bookID,book.BookName,lend.lend_date,lend.due_date from student inner join book inner join lend where book.bookID = lend.bookID and student.studentID = lend.studentID and lend.return_status = 'YES' " ;
//    try (
//            Connection conn = CreateConnection();
//            PreparedStatement stmt = conn.prepareStatement(query);
//         ResultSet rs = stmt.executeQuery()) {
// 
//          jTable1.setModel(DbUtils.resultSetToTableModel(rs)); // Set the table model
//        
//          conn.close();
//
//        
//    } catch (SQLException e) {
//        e.printStackTrace();
//     JOptionPane.showMessageDialog(null, "Database Error lending books: " + e.getMessage());
//    }
//          
//          }
//          public void totalbooks(){
////    String query = "SELECT lend.bookID, student.name, lend.lend_date, lend.due_date FROM lend JOIN student ON lend.studentID = student.studentID WHERE return_status = 'No' ";
//  String query = "SELECT *, (SELECT COUNT(*) FROM book) AS total_count FROM book;" ;
//    try (
//            Connection conn = CreateConnection();
//            PreparedStatement stmt = conn.prepareStatement(query);
//         ResultSet rs = stmt.executeQuery()) {
// 
//          jTable3.setModel(DbUtils.resultSetToTableModel(rs)); // Set the table model
//        
//          conn.close();
//
//        
//    } catch (SQLException e) {
//        e.printStackTrace();
//     JOptionPane.showMessageDialog(null, "Database Error lending books: " + e.getMessage());
//    }
//
//          }
//    
//       public void totalstudents(){
// 
//  String query = "SELECT *, (SELECT COUNT(*) FROM student) AS total_count FROM student;" ;
//    try (
//            Connection conn = CreateConnection();
//            PreparedStatement stmt = conn.prepareStatement(query);
//         ResultSet rs = stmt.executeQuery()) {
// 
//          jTable4.setModel(DbUtils.resultSetToTableModel(rs)); // Set the table model
//        
//          conn.close();
//
//
//    } catch (SQLException e) {
//        e.printStackTrace();
//     JOptionPane.showMessageDialog(null, "Database Error lending books: " + e.getMessage());
//    }
//};
       
    public void LendingStatsChart() {
        setTitle("Lending Statistics Bar Chart");
        setSize(400, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
                setExtendedState(ABORT);
        setLocationRelativeTo(jButton2);
        new Statistics().setVisible(true);
        // Create dataset from DB
        DefaultCategoryDataset dataset = createDataset();

        // Create chart
        JFreeChart barChart = ChartFactory.createBarChart(
                "Library Lending Statistics",
                "Status",
                "Count",
                dataset
        );

        ChartPanel panel = new ChartPanel(barChart);
        setContentPane(panel);
    }
    private DefaultCategoryDataset createDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        int lended = 0;
        int returned = 0;

        String queryLend = "SELECT COUNT(*) FROM lend WHERE return_status = 'No'";
        String queryReturned = "SELECT COUNT(*) FROM lend WHERE return_status = 'Yes'";
 try (
                Connection conn = 
                        CreateConnection();
                PreparedStatement stmtLend = conn.prepareStatement(queryLend);
                PreparedStatement stmtReturned = conn.prepareStatement(queryReturned);
        ) {
            ResultSet rs1 = stmtLend.executeQuery();
            if (rs1.next()) lended = rs1.getInt(1);

            ResultSet rs2 = stmtReturned.executeQuery();
            if (rs2.next()) returned = rs2.getInt(1);

            dataset.addValue(lended, "Books", "Lended");
            dataset.addValue(returned, "Books", "Returned");
   } catch (SQLException e) {
            e.printStackTrace();  };
            return dataset;
    }; 
 
    public void StudentsBooksPieChart() {
        setTitle("Students vs Books Pie Chart");
        setSize(400, 400);
        
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(jButton6);
             setExtendedState(ABORT);
        new Statistics().setVisible(true);
        DefaultPieDataset dataset = new DefaultPieDataset();
        int totalStudents = 0;
        int totalBooks = 0;
 try (
                Connection conn = CreateConnection();
                Statement stmt = conn.createStatement()
        ) {
            ResultSet rs1 = stmt.executeQuery("SELECT COUNT(*) FROM student");
            if (rs1.next()) totalStudents = rs1.getInt(1);

            ResultSet rs2 = stmt.executeQuery("SELECT COUNT(*) FROM book");
            if (rs2.next()) totalBooks = rs2.getInt(1);

            dataset.setValue("Students", totalStudents);
            dataset.setValue("Books", totalBooks);

        } catch (SQLException e) {
            e.printStackTrace();
        }

        JFreeChart chart = ChartFactory.createPieChart(
                "Students vs Books",
                dataset,
                true,
                true,
                false
        );

        ChartPanel panel = new ChartPanel(chart);
        setContentPane(panel);
    }
     
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        lendedbook(); 
LendingStatsChart();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        totalbooks();
 StudentsBooksPieChart();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//         returnedbook();
LendingStatsChart();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//    totalstudents();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
//CREATED BY MANSOOR or MNS GitHub: MnsDew
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistics().setVisible(true);
                 //Get the database connection based on your requrements!!
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
